# Generated by Django 4.2.6 on 2023-10-17 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
